// <auto-generated />
using System;
using Dharmatlas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dharmatlas.Persistence.Migrations
{
    [DbContext(typeof(DharmatlasDbContext))]
    [Migration("20260913234943_MultilingualSearchFidelity")]
    partial class MultilingualSearchFidelity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dharmatlas.Domain.Entities.AiDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InputReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_reference_id");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("PromptRef")
                        .HasColumnType("text")
                        .HasColumnName("prompt_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SuggestionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggestion_json");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InputReferenceId" }, "ix_ai_drafts_input");

                    b.HasIndex(new[] { "Status" }, "ix_ai_drafts_status");

                    b.ToTable("ai_drafts", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Certainty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certainty");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interpretation");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ids");

                    b.Property<string>("SourceLocator")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_locator");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubjectEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_entity_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Certainty", "Status" }, "ix_claims_certainty_status");

                    b.HasIndex(new[] { "SubjectEntityId" }, "ix_claims_subject");

                    b.HasIndex(new[] { "SubjectEntityId", "Status" }, "ix_claims_subject_publication");

                    b.ToTable("claims", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Contributor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasFilter("external_subject IS NOT NULL");

                    b.ToTable("contributors", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("entity_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("entity_type")
                        .HasDatabaseName("ix_entities_type");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator<string>("entity_type").HasValue("Entity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.EntityName", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_value");

                    b.Property<string>("Romanization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("romanization");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("script");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedValue")
                        .HasDatabaseName("ix_entity_names_normalized_value");

                    b.HasIndex(new[] { "Language", "Value" }, "ix_entity_names_lang_value");

                    b.HasIndex(new[] { "Romanization" }, "ix_entity_names_romanization");

                    b.HasIndex(new[] { "Script" }, "ix_entity_names_script");

                    b.HasIndex(new[] { "Value" }, "ix_entity_names_value");

                    b.HasIndex(new[] { "Value", "EntityId" }, "ix_entity_names_value_entity");

                    b.HasIndex(new[] { "EntityId", "Language" }, "ux_entity_names_primary_language")
                        .IsUnique()
                        .HasFilter("is_primary = true");

                    b.ToTable("entity_names", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Certainty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certainty");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ids");

                    b.Property<Guid>("ToEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_entity_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FromEntityId", "ToEntityId" }, "ix_relationships_endpoints");

                    b.HasIndex(new[] { "FromEntityId", "Id" }, "ix_relationships_from_id");

                    b.HasIndex(new[] { "ToEntityId", "Id" }, "ix_relationships_to_id");

                    b.HasIndex(new[] { "Type" }, "ix_relationships_type");

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Revision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("text")
                        .HasColumnName("changed_fields_json");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("PriorValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prior_value_json");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ids");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TargetId" }, "ix_revisions_target");

                    b.ToTable("revisions", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("PublisherOrCollection")
                        .HasColumnType("text")
                        .HasColumnName("publisher_or_collection");

                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Identifier" }, "ix_sources_identifier");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Status" }, "ix_submissions_status");

                    b.HasIndex(new[] { "TargetId" }, "ix_submissions_target");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Event", b =>
                {
                    b.HasBaseType("Dharmatlas.Domain.Entities.Entity");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Certainty")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("certainty");

                    b.Property<Guid?>("PlaceId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Region")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.HasIndex(new[] { "Category", "Region" }, "ix_events_category_region");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Institution", b =>
                {
                    b.HasBaseType("Dharmatlas.Domain.Entities.Entity");

                    b.Property<string>("Certainty")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("certainty");

                    b.Property<string>("InstitutionalForm")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlaceId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("source_ids");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator().HasValue("Institution");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Person", b =>
                {
                    b.HasBaseType("Dharmatlas.Domain.Entities.Entity");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Place", b =>
                {
                    b.HasBaseType("Dharmatlas.Domain.Entities.Entity");

                    b.Property<string>("Certainty")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("certainty");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("ModernName")
                        .HasColumnType("text")
                        .HasColumnName("modern_name");

                    b.Property<string>("Region")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("source_ids");

                    b.HasIndex(new[] { "Latitude", "Longitude" }, "ix_places_coords");

                    b.HasIndex(new[] { "Kind" }, "ix_places_kind");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator().HasValue("Place");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Text", b =>
                {
                    b.HasBaseType("Dharmatlas.Domain.Entities.Entity");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text")
                        .HasColumnName("original_language");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Tradition", b =>
                {
                    b.HasBaseType("Dharmatlas.Domain.Entities.Entity");

                    b.Property<string>("Region")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.ToTable("entities", (string)null);

                    b.HasDiscriminator().HasValue("Tradition");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.AiDraft", b =>
                {
                    b.OwnsMany("Dharmatlas.Domain.Entities.AiReviewDecision", "Decisions", b1 =>
                        {
                            b1.Property<Guid>("ai_draft_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Decision")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("decision");

                            b1.Property<string>("EditedSuggestionJson")
                                .HasColumnType("text")
                                .HasColumnName("edited_suggestion_json");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ReviewerId")
                                .HasColumnType("uuid")
                                .HasColumnName("reviewer_id");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("timestamp");

                            b1.HasKey("ai_draft_id", "Id");

                            b1.ToTable("ai_draft_decisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ai_draft_id");
                        });

                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Submission", b =>
                {
                    b.OwnsMany("Dharmatlas.Domain.Entities.ReviewDecision", "Decisions", b1 =>
                        {
                            b1.Property<Guid>("submission_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CorrelationId")
                                .HasColumnType("text")
                                .HasColumnName("correlation_id");

                            b1.Property<string>("Decision")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("decision");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ReviewerId")
                                .HasColumnType("uuid")
                                .HasColumnName("reviewer_id");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("timestamp");

                            b1.HasKey("submission_id", "Id");

                            b1.ToTable("submission_decisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("submission_id");
                        });

                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Event", b =>
                {
                    b.OwnsOne("Dharmatlas.Domain.ValueObjects.HistoricalDate", "When", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayExpression")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("when_display");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("when_kind");

                            b1.Property<int?>("NormalizedLowerBound")
                                .HasColumnType("integer")
                                .HasColumnName("when_lower");

                            b1.Property<int?>("NormalizedUpperBound")
                                .HasColumnType("integer")
                                .HasColumnName("when_upper");

                            b1.HasKey("EventId");

                            b1.HasIndex(new[] { "NormalizedLowerBound", "NormalizedUpperBound" }, "ix_events_when_range");

                            b1.ToTable("entities");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("When");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Institution", b =>
                {
                    b.OwnsOne("Dharmatlas.Domain.ValueObjects.HistoricalDate", "Activity", b1 =>
                        {
                            b1.Property<Guid>("InstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayExpression")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("activity_display");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("activity_kind");

                            b1.Property<int?>("NormalizedLowerBound")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("activity_lower");

                            b1.Property<int?>("NormalizedUpperBound")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("activity_upper");

                            b1.HasKey("InstitutionId");

                            b1.HasIndex(new[] { "NormalizedLowerBound", "NormalizedUpperBound" }, "ix_institutions_activity_range");

                            b1.ToTable("entities");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionId");
                        });

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Dharmatlas.Domain.Entities.Place", b =>
                {
                    b.OwnsOne("Dharmatlas.Domain.ValueObjects.HistoricalDate", "Activity", b1 =>
                        {
                            b1.Property<Guid>("PlaceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayExpression")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("activity_display");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("activity_kind");

                            b1.Property<int?>("NormalizedLowerBound")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("activity_lower");

                            b1.Property<int?>("NormalizedUpperBound")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("activity_upper");

                            b1.HasKey("PlaceId");

                            b1.HasIndex(new[] { "NormalizedLowerBound", "NormalizedUpperBound" }, "ix_places_activity_range");

                            b1.ToTable("entities");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.Navigation("Activity");
                });
#pragma warning restore 612, 618
        }
    }
}
